import { AluminiumProfileSector } from '../types/manufacturingSystems';

export const ALUMINIUM_PROFILE_DATABASE: AluminiumProfileSector[] = [
  // --- قطاعات ألوميتال المطابخ القياسية (STANDARD ALUMINIUM PROFILES) ---
  {
    id: 'prof-alum-tube-25',
    code: 'AL-TUBE-25',
    name: 'علبة شاسيه رئيسية 25×25 مم (تانجو)',
    nameEn: 'Tango Square Tube Frame 25x25mm',
    system: 'aluminium',
    category: 'vertical-frame',
    width: 25,
    height: 25,
    thickness: 1.3,
    standardBarLength: 6000,
    weightKgPerMeter: 0.38,
    pricePerMeter: 95,
    sawKerfAllowance: 4,
    connectionDeduction: 25,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    compatibleConnectors: ['زاوية بلاستيك تجميع 25 مم', 'زاوية ألومنيوم تجميع داخلية'],
    description: 'قائم وعوارض الشاسيه الداخلي الرئيسي للوحدة السفلية والعلوية',
  },
  {
    id: 'prof-alum-door-45',
    code: 'AL-DOOR-45',
    name: 'فريم ضلفة ألومنيوم 45 مم (شطف 45°)',
    nameEn: '45mm Mitred Door Frame Profile',
    system: 'aluminium',
    category: 'door-frame',
    width: 45,
    height: 20,
    thickness: 1.4,
    standardBarLength: 6000,
    weightKgPerMeter: 0.52,
    pricePerMeter: 140,
    sawKerfAllowance: 4,
    connectionDeduction: 0,
    defaultCutAngleLeft: 45,
    defaultCutAngleRight: 45,
    compatibleConnectors: ['جونيا زاوية حديد مجلفن 45°', 'كاوتش زجاج وضلف'],
    description: 'بروفايل إطار الضلفة المودرن مع مجرى حشوة 4 مم أو زجاج',
  },
  {
    id: 'prof-alum-shelf-supp',
    code: 'AL-SHELF-U',
    name: 'حامل ومجرى رفوف ألومنيوم حرف U',
    nameEn: 'U-Channel Shelf Support Profile',
    system: 'aluminium',
    category: 'shelf-support',
    width: 20,
    height: 15,
    thickness: 1.2,
    standardBarLength: 6000,
    weightKgPerMeter: 0.22,
    pricePerMeter: 65,
    sawKerfAllowance: 4,
    connectionDeduction: 10,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    description: 'قناة تثبيت الرفوف الداخلية وتوزيع الأوزان',
  },
  {
    id: 'prof-alum-gola-l',
    code: 'AL-GOLA-L',
    name: 'مقبض بروفايل جولا مخفي حرف L',
    nameEn: 'Gola Profile Handleless L-Shape',
    system: 'aluminium',
    category: 'handle-gola',
    width: 55,
    height: 25,
    thickness: 1.5,
    standardBarLength: 6000,
    weightKgPerMeter: 0.45,
    pricePerMeter: 160,
    sawKerfAllowance: 4,
    connectionDeduction: 0,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    description: 'بروفايل علوي للفتح المودرن بدون مقابض بارزة (Handless)',
  },

  // --- قطاعات مطابخ الكلادينج (CLADDING SYSTEM PROFILES) ---
  {
    id: 'prof-clad-frame-30',
    code: 'CLAD-FRAME-30',
    name: 'شاسيه كلادينج مقوى 30×30 مم',
    nameEn: 'Heavy Duty Cladding Frame 30x30mm',
    system: 'cladding',
    category: 'vertical-frame',
    width: 30,
    height: 30,
    thickness: 1.5,
    standardBarLength: 6000,
    weightKgPerMeter: 0.58,
    pricePerMeter: 125,
    sawKerfAllowance: 4,
    connectionDeduction: 30,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    description: 'شاسيه هيكلي لتثبيت ألواح الكلادينج 4 مم Alubond بواسطة السيليكون الهيكلي والمسامير',
  },
  {
    id: 'prof-clad-edge-f',
    code: 'CLAD-EDGE-F',
    name: 'بروفايل قشاط إطار كلادينج حرف F',
    nameEn: 'F-Profile Cladding Edge Trim',
    system: 'cladding',
    category: 'door-frame',
    width: 25,
    height: 18,
    thickness: 1.2,
    standardBarLength: 6000,
    weightKgPerMeter: 0.35,
    pricePerMeter: 90,
    sawKerfAllowance: 4,
    connectionDeduction: 0,
    defaultCutAngleLeft: 45,
    defaultCutAngleRight: 45,
    description: 'إطار إنهاء محيطي لشيتات الكلادينج لحماية الحواف وعزل الرطوبة',
  },

  // --- قطاعات الخشمونيوم (KHASHMOUNIUM WOODGRAIN PROFILES) ---
  {
    id: 'prof-khash-box-heavy',
    code: 'KHASH-BOX-35',
    name: 'قائم خشمونيوم مضلع بتجزيعة الخشب (Jumbo)',
    nameEn: 'Khashmounium Woodgrain Jumbo Sector',
    system: 'khashmounium',
    category: 'vertical-frame',
    width: 35,
    height: 35,
    thickness: 1.6,
    standardBarLength: 6000,
    weightKgPerMeter: 0.72,
    pricePerMeter: 185,
    sawKerfAllowance: 4,
    connectionDeduction: 35,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    description: 'قطاع خشمونيوم دهان إلكتروستاتيك عالي المقاومة بتأثير ثمرة الخشب الطبيعي',
  },
  {
    id: 'prof-khash-door-classic',
    code: 'KHASH-DOOR-55',
    name: 'فريم ضلفة خشمونيوم كلاسيك 55 مم (45°)',
    nameEn: 'Khashmounium Classic Door Frame 55mm',
    system: 'khashmounium',
    category: 'door-frame',
    width: 55,
    height: 22,
    thickness: 1.5,
    standardBarLength: 6000,
    weightKgPerMeter: 0.68,
    pricePerMeter: 195,
    sawKerfAllowance: 4,
    connectionDeduction: 0,
    defaultCutAngleLeft: 45,
    defaultCutAngleRight: 45,
    compatibleConnectors: ['زاوية خشمونيوم كبس إيطالي', 'مسامير ريفيت ألومنيوم'],
    description: 'فريم ضلفة خارجي مشطوف 45 درجة مع مجرى حشوة فايبر أو زجاج مصنفر',
  },

  // --- قطاعات الفايبر جلاس (FIBRE SYSTEM PROFILES) ---
  {
    id: 'prof-fibre-frame',
    code: 'FIBRE-FRAME-20',
    name: 'قائم شاسيه فايبر عازل 20×20 مم',
    nameEn: 'Fibre Kitchen Skeleton Tube 20x20mm',
    system: 'fibre',
    category: 'vertical-frame',
    width: 20,
    height: 20,
    thickness: 1.2,
    standardBarLength: 6000,
    weightKgPerMeter: 0.32,
    pricePerMeter: 85,
    sawKerfAllowance: 4,
    connectionDeduction: 20,
    defaultCutAngleLeft: 90,
    defaultCutAngleRight: 90,
    description: 'شاسيه خفيف ومقاوم للأحماض والمياه لتثبيت ألواح الفايبر جلاس',
  },
];
