import { ApplianceType } from '../types';

export interface ApplianceTemplate {
  type: ApplianceType;
  name: string;
  nameEn: string;
  category: 'cooling' | 'cooking' | 'cleaning' | 'ventilation' | 'sinks';
  description: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultDepth: number;
  defaultZ: number;
  clearanceSides: number;
  clearanceBack: number;
  clearanceTop: number;
  standardWidths: number[];
  icon: string;
  isBuiltIn?: boolean;
}

export const APPLIANCE_LIBRARY: ApplianceTemplate[] = [
  // --- تبريد وثلاجات ---
  {
    type: 'fridge-freestanding',
    name: 'ثلاجة قائمة حرة (Freestanding)',
    nameEn: 'Freestanding Refrigerator',
    category: 'cooling',
    description: 'ثلاجة دولابي أو فريزر سفلي مع مسافات تهوية',
    defaultWidth: 900,
    defaultHeight: 1850,
    defaultDepth: 680,
    defaultZ: 0,
    clearanceSides: 50,
    clearanceBack: 50,
    clearanceTop: 100,
    standardWidths: [600, 700, 800, 900, 1000],
    icon: 'Refrigerator',
    isBuiltIn: false,
  },
  {
    type: 'fridge-builtin',
    name: 'ثلاجة بلت إن مدمجة',
    nameEn: 'Built-in Refrigerator',
    category: 'cooling',
    description: 'ثلاجة مخفية بالكامل خلف ضلف الخشب',
    defaultWidth: 600,
    defaultHeight: 1780,
    defaultDepth: 550,
    defaultZ: 100,
    clearanceSides: 0,
    clearanceBack: 50,
    clearanceTop: 50,
    standardWidths: [600, 750, 900],
    icon: 'Refrigerator',
    isBuiltIn: true,
  },

  // --- طهي وأفران ---
  {
    type: 'cooktop-induction',
    name: 'مسطح بلت إن (غاز / كهرباء)',
    nameEn: 'Induction / Gas Cooktop',
    category: 'cooking',
    description: 'مسطح 4 أو 5 شعلات ساقط بالرخام',
    defaultWidth: 600,
    defaultHeight: 50,
    defaultDepth: 520,
    defaultZ: 850,
    clearanceSides: 50,
    clearanceBack: 50,
    clearanceTop: 650,
    standardWidths: [600, 750, 800, 900],
    icon: 'Flame',
    isBuiltIn: true,
  },
  {
    type: 'cooker-range',
    name: 'بوتجاز قائم حر بالفرن',
    nameEn: 'Freestanding Range Cooker',
    category: 'cooking',
    description: 'بوتجاز شيف متكامل 90 سم مع فرن سفلي كبير',
    defaultWidth: 900,
    defaultHeight: 900,
    defaultDepth: 600,
    defaultZ: 0,
    clearanceSides: 5,
    clearanceBack: 20,
    clearanceTop: 750,
    standardWidths: [600, 900, 1000, 1200],
    icon: 'CookingPot',
    isBuiltIn: false,
  },
  {
    type: 'oven-builtin',
    name: 'فرن كهربائي مدمج (60 سم)',
    nameEn: 'Built-in Single Oven',
    category: 'cooking',
    description: 'فرن بلت إن قياسي بتبريد مروحة وشاشة ديجيتال',
    defaultWidth: 595,
    defaultHeight: 595,
    defaultDepth: 560,
    defaultZ: 100,
    clearanceSides: 0,
    clearanceBack: 40,
    clearanceTop: 0,
    standardWidths: [600],
    icon: 'Flame',
    isBuiltIn: true,
  },
  {
    type: 'microwave-builtin',
    name: 'ميكروويف مدمج (Built-in)',
    nameEn: 'Built-in Microwave',
    category: 'cooking',
    description: 'ميكروويف وشواية مدمجة بالدولاب العلوي أو البرج',
    defaultWidth: 595,
    defaultHeight: 385,
    defaultDepth: 400,
    defaultZ: 1400,
    clearanceSides: 0,
    clearanceBack: 30,
    clearanceTop: 0,
    standardWidths: [600],
    icon: 'Radio',
    isBuiltIn: true,
  },

  // --- غسيل وصحون ---
  {
    type: 'dishwasher',
    name: 'غسالة صحون مدمجة',
    nameEn: 'Integrated Dishwasher',
    category: 'cleaning',
    description: 'غسالة صحون 60 سم تحت الرخام مخفية بالكامل',
    defaultWidth: 600,
    defaultHeight: 820,
    defaultDepth: 570,
    defaultZ: 0,
    clearanceSides: 0,
    clearanceBack: 30,
    clearanceTop: 0,
    standardWidths: [450, 600],
    icon: 'Sparkles',
    isBuiltIn: true,
  },
  {
    type: 'washing-machine',
    name: 'غسالة ملابس أمامية',
    nameEn: 'Front-load Washing Machine',
    category: 'cleaning',
    description: 'غسالة ملابس بفتحة أمامية تسقط أسفل الكاونترتوب',
    defaultWidth: 600,
    defaultHeight: 850,
    defaultDepth: 600,
    defaultZ: 0,
    clearanceSides: 10,
    clearanceBack: 40,
    clearanceTop: 10,
    standardWidths: [600],
    icon: 'Disc',
    isBuiltIn: false,
  },

  // --- شفاطات ---
  {
    type: 'hood-wall',
    name: 'شفاط جداري ديكوري (هرمي/حرف T)',
    nameEn: 'Wall Chimney Hood',
    category: 'ventilation',
    description: 'شفاط ستانلس ستيل مع مدخنة رأسية وفلاتر كربونية',
    defaultWidth: 900,
    defaultHeight: 650,
    defaultDepth: 500,
    defaultZ: 1550,
    clearanceSides: 0,
    clearanceBack: 0,
    clearanceTop: 0,
    standardWidths: [600, 900, 1200],
    icon: 'Fan',
    isBuiltIn: false,
  },
  {
    type: 'hood-integrated',
    name: 'شفاط بلت إن مخفي داخل الوحدة',
    nameEn: 'Integrated Canopy Hood',
    category: 'ventilation',
    description: 'شفاط غاطس بالكامل داخل الكابينة العلوية',
    defaultWidth: 600,
    defaultHeight: 300,
    defaultDepth: 320,
    defaultZ: 1450,
    clearanceSides: 0,
    clearanceBack: 0,
    clearanceTop: 0,
    standardWidths: [600, 900],
    icon: 'Wind',
    isBuiltIn: true,
  },

  // --- أحواض وخلاطات ---
  {
    type: 'sink-single',
    name: 'حوض عين واحدة مع خلاط شجرة',
    nameEn: 'Single Bowl Sink & Mixer',
    category: 'sinks',
    description: 'حوض ساقط تحت الرخام مع خلاط رقبة وزة نحاسي/كروم',
    defaultWidth: 550,
    defaultHeight: 200,
    defaultDepth: 450,
    defaultZ: 850,
    clearanceSides: 50,
    clearanceBack: 50,
    clearanceTop: 0,
    standardWidths: [450, 550, 600],
    icon: 'Droplets',
    isBuiltIn: true,
  },
  {
    type: 'sink-double',
    name: 'حوض عينين مع صفاية وخلاط',
    nameEn: 'Double Bowl Sink & Mixer',
    category: 'sinks',
    description: 'حوض كبير عينين لغسيل الأواني والخضروات',
    defaultWidth: 860,
    defaultHeight: 220,
    defaultDepth: 500,
    defaultZ: 850,
    clearanceSides: 50,
    clearanceBack: 50,
    clearanceTop: 0,
    standardWidths: [800, 860, 1000, 1160],
    icon: 'Droplet',
    isBuiltIn: true,
  },
];
