import { CabinetItem, CabinetCategory, CabinetType } from '../types';

export interface CabinetTemplate {
  category: CabinetCategory;
  type: CabinetType;
  name: string;
  description: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultDepth: number;
  defaultZ: number; // Elevation from floor
  doorCount: number;
  drawerCount: number;
  shelfCount: number;
  doorHinge: 'left' | 'right' | 'double' | 'top' | 'none';
  standardWidths: number[];
  icon: string;
  hasSinkCutout?: boolean;
  hasApplianceCavity?: boolean;
  applianceCavityHeight?: number;
  applianceCavityZ?: number;
}

export const CABINET_LIBRARY: CabinetTemplate[] = [
  // --- BASE CABINETS ---
  {
    category: 'base',
    type: 'base-single-door',
    name: 'Single Door Base',
    description: 'Standard 1-door base cabinet with 1 adjustable shelf',
    defaultWidth: 600,
    defaultHeight: 720, // Carcase height (excluding plinth)
    defaultDepth: 560,
    defaultZ: 100, // Plinth height
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
  },
  {
    category: 'base',
    type: 'base-double-door',
    name: 'Double Door Base',
    description: 'Wide 2-door base cabinet with 1 adjustable shelf',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
  },
  {
    category: 'base',
    type: 'base-drawers-3',
    name: '3-Drawer Base',
    description: '1 top shallow cutlery drawer + 2 deep pan drawers',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 3,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [450, 500, 600, 800, 900, 1000],
    icon: 'Rows3',
  },
  {
    category: 'base',
    type: 'base-drawers-2',
    name: '2-Drawer Deep Base',
    description: '2 deep pot & pan drawers with high load slides',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 2,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Rows2',
  },
  {
    category: 'base',
    type: 'base-drawers-4',
    name: '4-Drawer Base',
    description: '4 multi-purpose storage drawers',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 4,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [450, 500, 600, 800],
    icon: 'Rows4',
  },
  {
    category: 'base',
    type: 'base-sink',
    name: 'Sink Base Unit',
    description: 'Reinforced base cabinet for sink bowl with plumbing recess',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'double',
    hasSinkCutout: true,
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Droplets',
  },
  {
    category: 'base',
    type: 'base-corner-l',
    name: 'L-Corner Base (90°)',
    description: 'L-shape 900x900 corner unit with bi-fold door or carousel',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 900,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [900, 1000],
    icon: 'CornerDownRight',
  },
  {
    category: 'base',
    type: 'base-corner-blind',
    name: 'Blind Corner Base',
    description: 'Straight corner unit with blind filler panel & pull-out basket',
    defaultWidth: 1050,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [1000, 1050, 1100, 1200],
    icon: 'BoxSelect',
  },
  {
    category: 'base',
    type: 'base-open-shelf',
    name: 'Open Shelf Base',
    description: 'Open decorative base unit with 2 fixed shelves',
    defaultWidth: 300,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'none',
    standardWidths: [200, 300, 450, 600],
    icon: 'LayoutPanelTop',
  },

  // --- WALL CABINETS ---
  {
    category: 'wall',
    type: 'wall-single-door',
    name: 'Single Door Wall Unit',
    description: 'Upper wall cabinet with 2 adjustable shelves',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450, // Standard 1450mm from floor (leaving 550mm backsplash gap above 900mm worktop)
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
  },
  {
    category: 'wall',
    type: 'wall-double-door',
    name: 'Double Door Wall Unit',
    description: 'Wide upper wall cabinet with 2 adjustable shelves',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
  },
  {
    category: 'wall',
    type: 'wall-lift-up',
    name: 'Lift-Up Flap Wall Unit',
    description: 'Horizontal flap cabinet with stay-lift gas springs',
    defaultWidth: 900,
    defaultHeight: 360,
    defaultDepth: 350,
    defaultZ: 1600,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'top',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'PanelTopOpen',
  },
  {
    category: 'wall',
    type: 'wall-open-shelf',
    name: 'Open Shelf Wall Unit',
    description: 'Open upper unit for spices, cookbooks or cups',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 330,
    defaultZ: 1450,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'none',
    standardWidths: [300, 450, 600, 800],
    icon: 'LayoutPanelTop',
  },
  {
    category: 'wall',
    type: 'wall-corner',
    name: 'Corner Wall Unit (600x600)',
    description: 'Diagonal or L-shaped wall corner storage',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 600,
    defaultZ: 1450,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [600, 650],
    icon: 'CornerUpRight',
  },

  // --- TALL CABINETS ---
  {
    category: 'tall',
    type: 'tall-pantry',
    name: 'Full Height Pantry',
    description: 'Floor-to-ceiling pantry with 4 adjustable shelves and lower pullouts',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 4,
    doorHinge: 'right',
    standardWidths: [450, 500, 600, 800],
    icon: 'Archive',
  },
  {
    category: 'tall',
    type: 'tall-oven-tower',
    name: 'Built-in Oven Tower',
    description: 'Tall unit with mid-height single oven cavity + storage doors/drawers',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 1,
    shelfCount: 2,
    doorHinge: 'right',
    hasApplianceCavity: true,
    applianceCavityHeight: 600,
    applianceCavityZ: 780, // Ergonomic eye-level oven height
    standardWidths: [600],
    icon: 'Flame',
  },
  {
    category: 'tall',
    type: 'tall-microwave-tower',
    name: 'Oven & Microwave Tower',
    description: 'Double cavity tall unit for built-in oven + compact microwave',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 2,
    shelfCount: 1,
    doorHinge: 'right',
    hasApplianceCavity: true,
    applianceCavityHeight: 1050,
    applianceCavityZ: 600,
    standardWidths: [600],
    icon: 'Layers',
  },
  {
    category: 'tall',
    type: 'tall-fridge-housing',
    name: 'Integrated Fridge Housing',
    description: 'Full-height unit designed to house built-in fridge freezer',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [600, 700, 900],
    icon: 'Refrigerator',
  },
  {
    category: 'tall',
    type: 'tall-utility',
    name: 'Utility / Broom Cabinet',
    description: 'Tall unit with partition for vacuum cleaner, ironing board and mops',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 3,
    doorHinge: 'left',
    standardWidths: [450, 500, 600],
    icon: 'Wrench',
  },

  // --- CUSTOM CABINET ---
  {
    category: 'custom',
    type: 'custom-box',
    name: 'Custom Dimension Cabinet',
    description: 'Fully custom box with user-defined width, height, depth & shelves',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [300, 450, 600, 800, 900, 1000, 1200],
    icon: 'Sliders',
  },
];
