import { CabinetCategory, CabinetType } from '../types';

export interface CabinetTemplate {
  category: CabinetCategory;
  type: CabinetType;
  name: string;
  nameEn: string;
  description: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultDepth: number;
  defaultZ: number;
  doorCount: number;
  drawerCount: number;
  shelfCount: number;
  doorHinge: 'left' | 'right' | 'double' | 'top' | 'none';
  standardWidths: number[];
  icon: string;
  hasSinkCutout?: boolean;
  hasApplianceCavity?: boolean;
  applianceCavityHeight?: number;
  applianceCavityZ?: number;
}

export const CABINET_LIBRARY: CabinetTemplate[] = [
  // --- وحدات سفلية (BASE CABINETS) ---
  {
    category: 'base',
    type: 'base-single-door',
    name: 'سفلي باب واحد',
    nameEn: 'Single Door Base',
    description: 'وحدة سفلية قياسية بباب واحد ورف داخلي قابل للتعديل',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
  },
  {
    category: 'base',
    type: 'base-double-door',
    name: 'سفلي بابين مزدوج',
    nameEn: 'Double Door Base',
    description: 'وحدة سفلية عريضة ببابين ورف داخلي قابل لتعديل الارتفاع',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
  },
  {
    category: 'base',
    type: 'base-drawers-3',
    name: 'سفلي 3 أدراج (معالق وحلل)',
    nameEn: '3-Drawer Base',
    description: 'درج علوي للملاعق والسكاكين + درجين عميقين للأواني والحلل',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 3,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [450, 500, 600, 800, 900, 1000],
    icon: 'Rows3',
  },
  {
    category: 'base',
    type: 'base-drawers-2',
    name: 'سفلي 2 درج حلل عميق',
    nameEn: '2-Drawer Deep Base',
    description: 'درجان عميقان مخصصان للأواني الكبيرة مع مجاري تحميل ثقيل',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 2,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Rows2',
  },
  {
    category: 'base',
    type: 'base-drawers-4',
    name: 'سفلي 4 أدراج متعددة',
    nameEn: '4-Drawer Base',
    description: '4 أدراج عملية لتخزين مستلزمات المطبخ والمفارش',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 4,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [450, 500, 600, 800],
    icon: 'Rows4',
  },
  {
    category: 'base',
    type: 'base-sink',
    name: 'وحدة حوض غسيل',
    nameEn: 'Sink Base Unit',
    description: 'وحدة مجهزة لتثبيت الحوض وتمديدات السباكة مع عوارض تقوية',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'double',
    hasSinkCutout: true,
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Droplets',
  },
  {
    category: 'base',
    type: 'base-corner-l',
    name: 'وحدة ركنة زاوية L (90°)',
    nameEn: 'L-Corner Base (90°)',
    description: 'وحدة زاوية 900×900 مم مزودة ببابين أو سلة دوارة (Carousel)',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 900,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [900, 1000],
    icon: 'CornerDownRight',
  },
  {
    category: 'base',
    type: 'base-corner-blind',
    name: 'وحدة ركنة مستقيمة (Blind)',
    nameEn: 'Blind Corner Base',
    description: 'وحدة زاوية مستقيمة مع بارتشن أعمى وسلة سحب ماجيك كورنر',
    defaultWidth: 1050,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [1000, 1050, 1100, 1200],
    icon: 'BoxSelect',
  },
  {
    category: 'base',
    type: 'base-open-shelf',
    name: 'سفلي رفوف مفتوحة',
    nameEn: 'Open Shelf Base',
    description: 'وحدة ديكورية سفلية برفوف مفتوحة لوضع الزيوت والبهارات',
    defaultWidth: 300,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'none',
    standardWidths: [200, 300, 450, 600],
    icon: 'LayoutPanelTop',
  },

  // --- وحدات علوية (WALL CABINETS) ---
  {
    category: 'wall',
    type: 'wall-single-door',
    name: 'علوي باب واحد',
    nameEn: 'Single Door Wall Unit',
    description: 'وحدة جدارية علوية بباب واحد ورفين داخليين',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
  },
  {
    category: 'wall',
    type: 'wall-double-door',
    name: 'علوي بابين مزدوج',
    nameEn: 'Double Door Wall Unit',
    description: 'وحدة جدارية علوية عريضة ببابين ورفين داخليين',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
  },
  {
    category: 'wall',
    type: 'wall-lift-up',
    name: 'علوي قلاب هيدروليك',
    nameEn: 'Lift-Up Flap Wall Unit',
    description: 'وحدة علوية بباب يفتح لأعلى بمساعدين غاز باستم',
    defaultWidth: 900,
    defaultHeight: 360,
    defaultDepth: 350,
    defaultZ: 1600,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'top',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'PanelTopOpen',
  },
  {
    category: 'wall',
    type: 'wall-open-shelf',
    name: 'علوي رفوف مفتوحة',
    nameEn: 'Open Shelf Wall Unit',
    description: 'وحدة علوية مفتوحة بدون أبواب للأكواب وكتب الطبخ',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 330,
    defaultZ: 1450,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'none',
    standardWidths: [300, 450, 600, 800],
    icon: 'LayoutPanelTop',
  },
  {
    category: 'wall',
    type: 'wall-corner',
    name: 'علوي ركنة زاوية (600×600)',
    nameEn: 'Corner Wall Unit',
    description: 'وحدة زاوية علوية مثلثة أو مربعة لاستغلال أركان المطبخ',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 600,
    defaultZ: 1450,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [600, 650],
    icon: 'CornerUpRight',
  },

  // --- وحدات طولية (TALL UNITS) ---
  {
    category: 'tall',
    type: 'tall-pantry',
    name: 'دولاب خزين طولي (Pantry)',
    nameEn: 'Full Height Pantry',
    description: 'دولاب تخزين كامل الارتفاع مع 4 رفوف قابلة للتعديل وسلال سحب',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 4,
    doorHinge: 'right',
    standardWidths: [450, 500, 600, 800],
    icon: 'Archive',
  },
  {
    category: 'tall',
    type: 'tall-oven-tower',
    name: 'برج فرن مدمج (Built-in)',
    nameEn: 'Built-in Oven Tower',
    description: 'وحدة طولية مزودة بتجويف لفرن بلت إن 60 سم على مستوى النظر',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 1,
    shelfCount: 2,
    doorHinge: 'right',
    hasApplianceCavity: true,
    applianceCavityHeight: 600,
    applianceCavityZ: 780,
    standardWidths: [600],
    icon: 'Flame',
  },
  {
    category: 'tall',
    type: 'tall-microwave-tower',
    name: 'برج فرن وميكروويف مدمج',
    nameEn: 'Oven & Microwave Tower',
    description: 'وحدة طولية مجهزة لفرن كهربائي + ميكروويف مدمج مع أدراج سفلية',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 2,
    shelfCount: 1,
    doorHinge: 'right',
    hasApplianceCavity: true,
    applianceCavityHeight: 1050,
    applianceCavityZ: 600,
    standardWidths: [600],
    icon: 'Layers',
  },
  {
    category: 'tall',
    type: 'tall-fridge-housing',
    name: 'دولاب ثلاجة مدمجة',
    nameEn: 'Integrated Fridge Housing',
    description: 'دولاب كامل الارتفاع لتبييت الثلاجة البلت إن مع تهوية خلفية',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [600, 700, 900],
    icon: 'Refrigerator',
  },
  {
    category: 'tall',
    type: 'tall-utility',
    name: 'دولاب خدمات ومكانس',
    nameEn: 'Utility / Broom Cabinet',
    description: 'دولاب طولي مع قاطع رأسي للمكنسة الكهربائية وطاولة الكي',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 3,
    doorHinge: 'left',
    standardWidths: [450, 500, 600],
    icon: 'Wrench',
  },

  // --- وحدات مخصصة (CUSTOM) ---
  {
    category: 'custom',
    type: 'custom-box',
    name: 'وحدة بمقاسات مخصصة',
    nameEn: 'Custom Dimension Cabinet',
    description: 'وحدة تصنيع خاصة بأبعاد ورفوف وأدراج حسب الطلب',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [300, 450, 600, 800, 900, 1000, 1200],
    icon: 'Sliders',
  },
];
