import { CabinetCategory, CabinetType } from '../types';

export interface CabinetTemplate {
  category: CabinetCategory;
  type: CabinetType;
  name: string;
  nameEn: string;
  description: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultDepth: number;
  defaultZ: number;
  doorCount: number;
  drawerCount: number;
  shelfCount: number;
  doorHinge: 'left' | 'right' | 'double' | 'top' | 'none';
  standardWidths: number[];
  icon: string;
  hasSinkCutout?: boolean;
  hasApplianceCavity?: boolean;
  applianceCavityHeight?: number;
  applianceCavityZ?: number;
  hasIntegratedLed?: boolean;
  verticalDividersCount?: number;
  isCeilingUnit?: boolean;
  flipUpDoor?: boolean;
  hasDishRack?: boolean;
  hasTopStretchers?: boolean;
  hasAluminumWaterproofBottom?: boolean;
  hasGolaProfile?: boolean;
  hasCrownMolding?: boolean;
  hasLightPelmet?: boolean;
  hasFillerPanel?: boolean;
  tag?: string;
}

export const CABINET_LIBRARY: CabinetTemplate[] = [
  // =========================================================================
  // 0. وحدات كيتشن ميكر الاحترافية (KITCHEN MAKER SIGNATURE UNITS)
  // =========================================================================
  {
    category: 'base',
    type: 'base-waterproof-sink',
    name: 'علبة حوض كيتشن ميكر (قاع ألومنيوم عازل + عوارض)',
    nameEn: 'KitchenMaker Waterproof Sink Base Unit',
    description: 'شاسيه حوض احترافي بعوارض علوية 10 سم للتهوية وتحمل الرخام مع قاع مصفح ألومنيوم معزول ضد تسريب المياه',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'double',
    hasSinkCutout: true,
    hasTopStretchers: true,
    hasAluminumWaterproofBottom: true,
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Droplets',
    tag: 'علبة حوض مصفحة',
  },
  {
    category: 'wall',
    type: 'wall-dish-rack',
    name: 'علبة مطبق تركي وصفاية أطباق ستانلس (Turkish Dish Rack)',
    nameEn: 'Wall Turkish Dish Rack Cabinet with Water Tray',
    description: 'علبة علوية مجهزة بصفاية أطباق ومطبق تركي ستانلس استيل 304 مع صينية سحب لتصريف قطرات المياه وقاع مفتوح',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 340,
    defaultZ: 1420,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    hasDishRack: true,
    standardWidths: [600, 800, 900, 1000],
    icon: 'PackageCheck',
    tag: 'مطبق تركي',
  },
  {
    category: 'base',
    type: 'base-spice-pullout',
    name: 'علبة ترولي توابل وزيوت سحاب (Spice Rack Pullout)',
    nameEn: 'Pullout Spice & Oil Rack Base Unit',
    description: 'علبة سفلية ضيقة مجهزة بميكانيزم ترولي استانلس استيل سحاب هيدروليك لحفظ التوابل وقزايز الزيوت',
    defaultWidth: 200,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [150, 200, 250, 300],
    icon: 'Sliders',
    tag: 'ترولي توابل',
  },
  {
    category: 'base',
    type: 'base-blind-magic-corner',
    name: 'علبة كورنر أعمى مع ماجيك كورنر (Blind Magic Corner)',
    nameEn: 'Blind Corner with Magic Pullout Trays',
    description: 'علبة ركنة عمياء تستغل زوايا المطبخ بالكامل مع سلال ماجيك كورنر معدنية تخرج بالكامل خارج العلبة',
    defaultWidth: 1050,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'left',
    standardWidths: [900, 1000, 1050, 1100, 1200],
    icon: 'CornerDownRight',
    tag: 'ماجيك كورنر',
  },
  {
    category: 'tall',
    type: 'tall-double-oven-microwave',
    name: 'برج بلت إن مزدوج (فرن + ميكروويف + درجين حلل)',
    nameEn: 'Tall Double Oven & Microwave Tower',
    description: 'برج مطبخ متكامل كيتشن ميكر بفتحتين للأجهزة البلت إن (فرن وميكروويف) مع درجين سفليين عميقين ودولاب علوي',
    defaultWidth: 600,
    defaultHeight: 2160,
    defaultDepth: 580,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 2,
    shelfCount: 2,
    doorHinge: 'right',
    hasApplianceCavity: true,
    applianceCavityHeight: 600,
    standardWidths: [600],
    icon: 'Tv',
    tag: 'برج فرن وميكروويف',
  },
  {
    category: 'base',
    type: 'base-filler-panel',
    name: 'فيلر تعويض جداري سفلي (Wall Scribe Infill Filler)',
    nameEn: 'Base Wall Scribe Filler Panel',
    description: 'بانوه فيلر تعويض 5-10 سم لوزن مقاسات المطبخ مع الحوائط غير المنتظمة وضمان فتح الضلف والأدراج بسلاسة',
    defaultWidth: 70,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'none',
    hasFillerPanel: true,
    standardWidths: [50, 70, 100],
    icon: 'Square',
    tag: 'فيلر تعويض',
  },

  // =========================================================================
  // 1. وحدات سفلية أساسية (STANDARD BASE CABINETS)
  // =========================================================================
  {
    category: 'base',
    type: 'base-single-door',
    name: 'سفلي باب واحد (مفصلي)',
    nameEn: 'Single Door Base Cabinet',
    description: 'وحدة سفلية قياسية بباب واحد ورف داخلي قابل لتعديل الارتفاع',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
    tag: 'سفلي',
  },
  {
    category: 'base',
    type: 'base-double-door',
    name: 'سفلي بابين مزدوج',
    nameEn: 'Double Door Base Cabinet',
    description: 'وحدة سفلية عريضة ببابين مفصليين ورف داخلي قابل لتعديل الارتفاع',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
    tag: 'سفلي',
  },
  {
    category: 'base',
    type: 'base-drawers-3',
    name: 'سفلي 3 أدراج (معالق وحلل تاندوم)',
    nameEn: '3-Drawer Base Cabinet',
    description: 'درج علوي للملاعق والسكاكين + درجين عميقين للأواني والحلل مع مجاري سوفت كلوز',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 3,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [450, 500, 600, 800, 900, 1000],
    icon: 'Rows3',
    tag: 'أدراج',
  },
  {
    category: 'base',
    type: 'base-drawers-2',
    name: 'سفلي 2 درج حلل عميق (Pots Drawers)',
    nameEn: '2-Drawer Deep Base',
    description: 'درجان عميقان مخصصان للأواني الكبيرة مع جوانب معدنية ومجاري تحميل 50 كجم',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 2,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Rows2',
    tag: 'أدراج',
  },
  {
    category: 'base',
    type: 'base-drawers-4',
    name: 'سفلي 4 أدراج متعددة الاستخدام',
    nameEn: '4-Drawer Multi Base',
    description: '4 أدراج عملية لتخزين مستلزمات المطبخ والمفارش وأدوات الضيافة',
    defaultWidth: 500,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 0,
    drawerCount: 4,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [400, 450, 500, 600],
    icon: 'LayoutGrid',
    tag: 'أدراج',
  },
  {
    category: 'base',
    type: 'base-sink',
    name: 'وحدة حوض غسيل (مع عازل رطوبة ألومنيوم)',
    nameEn: 'Sink Base Unit with Moisture Tray',
    description: 'مجهزة بقاع ألومنيوم معزول ضد تسريب المياه وتفريغ خلفي لتغذية وصرف السباكة',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Droplet',
    hasSinkCutout: true,
    tag: 'حوض',
  },

  // =========================================================================
  // 2. وحدات المطابخ التخصصية والتروليات (SPECIALIZED & WIRE ACCESSORIES)
  // =========================================================================
  {
    category: 'base',
    type: 'base-spice-pullout',
    name: 'ترولي بهارات وزيوت سحاب (15-20 سم)',
    nameEn: 'Pullout Spice & Bottle Rack',
    description: 'وحدة نحيفة مجهزة بسلة سلك ستانلس هيدروليك دورين للزيوت والتوابل',
    defaultWidth: 200,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [150, 200, 250, 300],
    icon: 'Package',
    tag: 'ترولي',
  },
  {
    category: 'base',
    type: 'base-trash-pullout',
    name: 'سفلي سلة مهملات سحابة مدمجة',
    nameEn: 'Integrated Waste & Recycling Pullout',
    description: 'درج سحاب أمامي يفتح ميكانيكياً مع سلتين لفرز النفايات وإعادة التدوير',
    defaultWidth: 450,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'none',
    standardWidths: [400, 450, 600],
    icon: 'Trash2',
    tag: 'إكسسوارات',
  },
  {
    category: 'base',
    type: 'base-gola-l',
    name: 'سفلي مودرن جولا L (بدون مقابض)',
    nameEn: 'Gola Profile Handleless Base (L-Type)',
    description: 'وحدة مطابخ مودرن مجهزة بمجرى بروفايل جولا علوي لفتح الضلفة والدرج من الأعلى بدون مقبض',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [450, 600, 800, 900],
    icon: 'Minus',
    tag: 'جولا مودرن',
  },
  {
    category: 'base',
    type: 'base-island-cabinet',
    name: 'وحدة جزيرة مطبخ مع تجليد خلفي',
    nameEn: 'Kitchen Island Unit with Back Cladding',
    description: 'وحدة سفلية مخصصة لجزر المطابخ المستقلة مع لوح تجليد ظهر فندقي وبار إفطار',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 600,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Square',
    tag: 'جزيرة',
  },

  // =========================================================================
  // 3. وحدات الأركان والزوايا (CORNER UNITS)
  // =========================================================================
  {
    category: 'corner',
    type: 'base-corner-l',
    name: 'ركنة زاوية L كلاسيك (90×90 سم)',
    nameEn: 'L-Shaped Corner Base (90x90)',
    description: 'وحدة ركنة مفصلية بزاوية قائمة 90 درجة توفر استغلالاً كاملاً لزوايا المطبخ',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 900,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'double',
    standardWidths: [850, 900, 950, 1000],
    icon: 'CornerDownRight',
    tag: 'ركنة',
  },
  {
    category: 'corner',
    type: 'base-magic-corner',
    name: 'ركنة ماجيك كورنر إيطالي سحاب',
    nameEn: 'Magic Corner Pullout Base (Left/Right)',
    description: 'مجهزة بميكانيزم ماجيك كورنر هيدروليك يخرج 4 سلال سلك ستانلس خارج الوحدة بالكامل',
    defaultWidth: 1050,
    defaultHeight: 720,
    defaultDepth: 560,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'right',
    standardWidths: [1000, 1050, 1100, 1200],
    icon: 'Sliders',
    tag: 'ركنة',
  },
  {
    category: 'corner',
    type: 'base-carousel-corner',
    name: 'ركنة صينية دوارة 270° (Lazy Susan)',
    nameEn: 'Carousel 270° Rotating Corner',
    description: 'وحدة ركنة مزودة بصينيتين دوارتين من الكروم والستانلس لسهولة الوصول للأواني والحلل',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 900,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    standardWidths: [900, 950, 1000],
    icon: 'RotateCw',
    tag: 'ركنة',
  },

  // =========================================================================
  // 4. وحدات علوية (WALL CABINETS)
  // =========================================================================
  {
    category: 'wall',
    type: 'wall-single-door',
    name: 'علوي باب واحد مفصلي',
    nameEn: 'Single Door Wall Cabinet',
    description: 'وحدة علوية قياسية بباب واحد ورفين داخليين',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'DoorClosed',
    tag: 'علوي',
  },
  {
    category: 'wall',
    type: 'wall-double-door',
    name: 'علوي بابين مزدوج',
    nameEn: 'Double Door Wall Cabinet',
    description: 'وحدة علوية عريضة ببابين مفصليين ورفين داخليين',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
    tag: 'علوي',
  },
  {
    category: 'wall',
    type: 'wall-lift-up',
    name: 'علوي قلاب هيدروليك مفرد (Lift-Up)',
    nameEn: 'Single Lift-Up Flap Wall Unit',
    description: 'باب قلاب يفتح للأعلى بباكم غاز هيدروليك ناعم يمنح وصولاً سهلاً للمحتويات',
    defaultWidth: 800,
    defaultHeight: 400,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'top',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'ChevronUp',
    tag: 'قلاب',
  },
  {
    category: 'wall',
    type: 'wall-aventos-bi-fold',
    name: 'علوي قلاب أفنتوس مزدوج (Blum Aventos HF)',
    nameEn: 'Bi-Fold Aventos HF Wall Unit',
    description: 'وحدة علوية فاخرة بضلفتين تفتحان للأعلى سوياً بميكانيزم بلوم أفنتوس الشهير',
    defaultWidth: 900,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'top',
    standardWidths: [800, 900, 1000, 1200],
    icon: 'FoldVertical',
    tag: 'قلاب',
  },
  {
    category: 'wall',
    type: 'wall-glass-vitrine',
    name: 'فيترينة زجاج فريم ألومنيوم أسود مع إضاءة LED',
    nameEn: 'Glass Display Vitrine with Integrated LED',
    description: 'فيترينة كاسات وتحف بضلف زجاج شفاف أو رمادي مدخن مع بروفايل ألومنيوم نحيف وإضاءة داخلية',
    defaultWidth: 800,
    defaultHeight: 720,
    defaultDepth: 350,
    defaultZ: 1450,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'double',
    standardWidths: [600, 800, 900, 1000],
    icon: 'Sparkles',
    hasIntegratedLed: true,
    tag: 'فيترينة',
  },
  {
    category: 'wall',
    type: 'wall-open-shelves',
    name: 'أرفف خشبية مفتوحة ديكورية (Open Shelves)',
    nameEn: 'Open Display Wall Shelves',
    description: 'وحدة رفوف مفتوحة بدون ضلف للتوابل والزرع والديكور المودرن',
    defaultWidth: 600,
    defaultHeight: 720,
    defaultDepth: 330,
    defaultZ: 1450,
    doorCount: 0,
    drawerCount: 0,
    shelfCount: 2,
    doorHinge: 'none',
    standardWidths: [300, 450, 600, 800, 900],
    icon: 'Layers',
    tag: 'مفتوح',
  },

  // =========================================================================
  // 4.5. علب علوية ممتدة للسقف بأبواب قلابة (CEILING LOFT & SOFFIT FLAP CABINETS)
  // =========================================================================
  {
    category: 'wall',
    type: 'wall-loft-lift-up',
    name: 'علوي سقفي قلاب باكم هيدروليك (Soffit Loft Flap)',
    nameEn: 'Top Ceiling Soffit Flap Cabinet (Lift-Up)',
    description: 'كابينة علوية تمتد حتى السقف بباب قلاب يفتح للأعلى بباكم غاز هيدروليكي للتخزين الموسمي',
    defaultWidth: 600,
    defaultHeight: 360,
    defaultDepth: 350,
    defaultZ: 2170,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'top',
    standardWidths: [450, 600, 800, 900, 1000, 1200],
    icon: 'ChevronUp',
    isCeilingUnit: true,
    flipUpDoor: true,
    tag: 'سقفي قلاب',
  },
  {
    category: 'wall',
    type: 'wall-loft-deep',
    name: 'علوي سقفي عميق فوق برج الثلاجة والأفران (Deep Loft Bridge)',
    nameEn: 'Deep Loft Bridge Cabinet (58cm Depth)',
    description: 'كابينة سقفية عميقة (58 سم) تركب أعلى برج الأفران أو الثلاجة بباب قلاب أفنتوس للأعلى',
    defaultWidth: 600,
    defaultHeight: 450,
    defaultDepth: 580,
    defaultZ: 2150,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 0,
    doorHinge: 'top',
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'FolderUp',
    isCeilingUnit: true,
    flipUpDoor: true,
    tag: 'سقفي عميق',
  },

  // =========================================================================
  // 5. أبراج ووحدات طولية (TALL TOWERS & PANTRIES)
  // =========================================================================
  {
    category: 'tall',
    type: 'tall-oven-tower',
    name: 'برج أفران وميكروويف مدمج (Double Oven Tower)',
    nameEn: 'Built-in Double Oven Tower',
    description: 'برج طولي مجهز بتجويف للفرن والميكروويف ودرج تخزين سفلي ودولاب علوي',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 580,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 1,
    shelfCount: 2,
    doorHinge: 'right',
    standardWidths: [600],
    icon: 'Tv',
    hasApplianceCavity: true,
    applianceCavityHeight: 600,
    applianceCavityZ: 850,
    tag: 'برج أجهزة',
  },
  {
    category: 'tall',
    type: 'tall-fridge-housing',
    name: 'دولاب ثلاجة بيلت إن مدمجة (Built-in Fridge)',
    nameEn: 'Integrated Built-in Refrigerator Tower',
    description: 'دولاب طولي مصمم للثلاجة والفريزر البيلت إن مع فتحات تهوية خلفية وسفلية',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 580,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 1,
    doorHinge: 'right',
    standardWidths: [600, 750, 900],
    icon: 'Box',
    tag: 'ثلاجة',
  },
  {
    category: 'tall',
    type: 'tall-pantry-pullout',
    name: 'دولاب تخزين مؤن تاندوم طولي (Tandem Pantry Larder)',
    nameEn: 'Full Height Tandem Pantry Pullout',
    description: 'دولاب تخزين مؤن كبير مع ميكانيزم تاندوم يسحب 6 سلال داخلية و 6 سلال على الباب',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 580,
    defaultZ: 100,
    doorCount: 1,
    drawerCount: 0,
    shelfCount: 6,
    doorHinge: 'right',
    standardWidths: [450, 500, 600],
    icon: 'Archive',
    tag: 'تخزين مؤن',
  },
  {
    category: 'tall',
    type: 'tall-cleaning-cabinet',
    name: 'دولاب مكانس ومعدات نظافة (Utility Cabinet)',
    nameEn: 'Cleaning & Utility Broom Cabinet',
    description: 'تقسيم داخلي رأسي طويل للمكانس والممسحة مع أرفف جانبية للمنظفات والمفروشات',
    defaultWidth: 600,
    defaultHeight: 2050,
    defaultDepth: 580,
    defaultZ: 100,
    doorCount: 2,
    drawerCount: 0,
    shelfCount: 3,
    doorHinge: 'right',
    verticalDividersCount: 1,
    standardWidths: [450, 500, 600],
    icon: 'SlidersHorizontal',
    tag: 'نظافة',
  },
];
