import { ManufacturingSystemTemplate } from '../types/manufacturingSystems';

export const PRESET_MANUFACTURING_TEMPLATES: ManufacturingSystemTemplate[] = [
  // 1. نظام الأخشاب والميلامين (MDF / WOOD 18MM)
  {
    id: 'sys-wood-mdf-18',
    name: 'نظام الخشب والميلامين (18 مم قياسي)',
    nameEn: 'Wood & Melamine 18mm System',
    systemType: 'wood',
    description: 'شاسيه خشب ميلامين 18 مم مع ظهر محفور 6 مم وقشاط ABS 1 مم وعوارض تثبيت علوية',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 1.0,
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1650,
    pricePerProfileBar: 0,
    costLaborPerMeter: 350,
    wasteFactorPercentage: 15,
  },

  // 2. نظام الألوميتال القياسي (ALUMINIUM TANGO SYSTEM)
  {
    id: 'sys-alum-tango',
    name: 'نظام الألوميتال القياسي (قطاع تانجو / شاسيه علبة)',
    nameEn: 'Standard Aluminium Tango System',
    systemType: 'aluminium',
    description: 'شاسيه ألوميتال علبة 25×25 مم مع فريم ضلفة مشطوف 45° وحشوات فايبر جلاس أو زجاج',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4, // 4mm Infill Sheet
    backPanelThickness: 3,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'AL-TUBE-25',
    horizontalFrameProfileId: 'AL-TUBE-25',
    doorFrameProfileId: 'AL-DOOR-45',
    shelfSupportProfileId: 'AL-SHELF-U',
    cornerJointDeduction: 25,
    pricePerSheet: 450, // Infill sheet
    pricePerProfileBar: 570, // 6m bar
    costLaborPerMeter: 450,
    wasteFactorPercentage: 10,
  },

  // 3. نظام الكلادينج الفاخر (CLADDING SYSTEM)
  {
    id: 'sys-cladding-alubond',
    name: 'نظام الكلادينج المقوى (Alubond 4mm)',
    nameEn: 'Heavy Duty Cladding Kitchen System',
    systemType: 'cladding',
    description: 'شاسيه معدني مقوى 30×30 مم مكسو بالكامل بشيتات كلادينج 4 مم مع إطارات حماية F-Trim',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4, // 4mm ACP Cladding Sheet
    backPanelThickness: 4,
    claddingSheetThickness: 4,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'CLAD-FRAME-30',
    horizontalFrameProfileId: 'CLAD-FRAME-30',
    doorFrameProfileId: 'CLAD-EDGE-F',
    cornerJointDeduction: 30,
    pricePerSheet: 850, // Cladding sheet 4mm
    pricePerProfileBar: 750,
    costLaborPerMeter: 550,
    wasteFactorPercentage: 12,
  },

  // 4. نظام الخشمونيوم الملكي (KHASHMOUNIUM SYSTEM)
  {
    id: 'sys-khashmounium-master',
    name: 'نظام الخشمونيوم الفاخر (قطاع جامبو بتجزيعة خشب)',
    nameEn: 'Master Khashmounium System',
    systemType: 'khashmounium',
    description: 'قطاعات خشمونيوم ثقيلة 35×35 مم بدهان مضلع كبس إيطالي وفريم ضلفة كلاسيك 55 مم مشطوف 45°',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4, // Woodgrain Infill Panel
    backPanelThickness: 3,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'KHASH-BOX-35',
    horizontalFrameProfileId: 'KHASH-BOX-35',
    doorFrameProfileId: 'KHASH-DOOR-55',
    cornerJointDeduction: 35,
    pricePerSheet: 650,
    pricePerProfileBar: 1110,
    costLaborPerMeter: 600,
    wasteFactorPercentage: 10,
  },

  // 5. نظام الفايبر جلاس العازل (FIBRE GLASS SYSTEM)
  {
    id: 'sys-fibre-waterproof',
    name: 'نظام الفايبر جلاس العازل للمياه والرطوبة',
    nameEn: 'Waterproof Fibre Kitchen System',
    systemType: 'fibre',
    description: 'شاسيه خفيف ومقاوم مع ألواح فايبر جلاس مصمتة مضادة للبكتيريا والرطوبة',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 3,
    backPanelThickness: 3,
    sawKerf: 3.5,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 3,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'FIBRE-FRAME-20',
    horizontalFrameProfileId: 'FIBRE-FRAME-20',
    cornerJointDeduction: 20,
    pricePerSheet: 520,
    pricePerProfileBar: 510,
    costLaborPerMeter: 400,
    wasteFactorPercentage: 10,
  },
];
