import { ManufacturingSystemTemplate } from '../types/manufacturingSystems';

export const PRESET_MANUFACTURING_TEMPLATES: ManufacturingSystemTemplate[] = [
  // 0. نظام كيتشن الاحترافي المتكامل (KITCHAN PRO INDUSTRIAL STANDARD)
  {
    id: 'sys-kitchan-pro',
    name: 'نظام كيتشن الاحترافي المتكامل (Kitchan Pro)',
    nameEn: 'Kitchan Arabic Industrial Standard',
    systemType: 'wood',
    supportedCategories: ['kitchen'],
    description: 'المعيار الصناعي المتطور في نظام كيتشن: شاسيه كونتر/MDF ميلامين مع عوارض علوية 10 سم، قاع حوض مصفح ألومنيوم، ظهر مفحور 6 مم، وقشاط PVC 2 مم للواجهات مع مسامير كونفرمات وتجميع مينيفكس',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.2,
    edgeBandingFront: 2.0,
    edgeBandingHidden: 0.4,
    doorReveal: 2.5,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 16,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1750,
    pricePerProfileBar: 0,
    costLaborPerMeter: 380,
    wasteFactorPercentage: 12,
  },

  // 1. نظام الأخشاب والميلامين للمطابخ (KITCHEN WOOD / MFC 18MM)
  {
    id: 'sys-kitchen-wood-18',
    name: 'نظام خشب وميلامين المطابخ (18 مم قياسي)',
    nameEn: 'Kitchen Wood & Melamine 18mm System',
    systemType: 'wood',
    supportedCategories: ['kitchen'],
    description: 'شاسيه خشب ميلامين 18 مم مقاوم للرطوبة مع ظهر محفور 6 مم وقشاط ABS 1 مم وعوارض تثبيت علوية',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 1.0,
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1650,
    pricePerProfileBar: 0,
    costLaborPerMeter: 350,
    wasteFactorPercentage: 15,
  },

  // 2. نظام الألوميتال للمطابخ (ALUMINIUM TANGO SYSTEM - KITCHEN ONLY)
  {
    id: 'sys-alum-tango',
    name: 'نظام ألوميتال مطابخ (قطاع تانجو / شاسيه علبة)',
    nameEn: 'Kitchen Aluminium Tango System',
    systemType: 'aluminium',
    supportedCategories: ['kitchen'],
    description: 'شاسيه ألوميتال علبة 25×25 مم مع فريم ضلفة مشطوف 45° وحشوات فايبر جلاس أو زجاج للمطابخ',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4,
    backPanelThickness: 3,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'AL-TUBE-25',
    horizontalFrameProfileId: 'AL-TUBE-25',
    doorFrameProfileId: 'AL-DOOR-45',
    shelfSupportProfileId: 'AL-SHELF-U',
    cornerJointDeduction: 25,
    pricePerSheet: 450,
    pricePerProfileBar: 570,
    costLaborPerMeter: 450,
    wasteFactorPercentage: 10,
  },

  // 3. نظام الكلادينج للمطابخ (CLADDING ALUBOND - KITCHEN ONLY)
  {
    id: 'sys-cladding-alubond',
    name: 'نظام كلادينج المطابخ المقوى (Alubond 4mm)',
    nameEn: 'Heavy Duty Kitchen Cladding System',
    systemType: 'cladding',
    supportedCategories: ['kitchen'],
    description: 'شاسيه معدني مقوى 30×30 مم مكسو بشيتات كلادينج 4 مم مع إطارات حماية F-Trim',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4,
    backPanelThickness: 4,
    claddingSheetThickness: 4,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'CLAD-FRAME-30',
    horizontalFrameProfileId: 'CLAD-FRAME-30',
    doorFrameProfileId: 'CLAD-EDGE-F',
    cornerJointDeduction: 30,
    pricePerSheet: 850,
    pricePerProfileBar: 750,
    costLaborPerMeter: 550,
    wasteFactorPercentage: 12,
  },

  // 4. نظام الخشمونيوم الملكي للمطابخ (KHASHMOUNIUM - KITCHEN ONLY)
  {
    id: 'sys-khashmounium-master',
    name: 'نظام خشمونيوم المطابخ الفاخر (قطاع جامبو بتجزيعة خشب)',
    nameEn: 'Master Kitchen Khashmounium System',
    systemType: 'khashmounium',
    supportedCategories: ['kitchen'],
    description: 'قطاعات خشمونيوم ثقيلة 35×35 مم بدهان مضلع كبس إيطالي وفريم ضلفة كلاسيك 55 مم',
    standardSheetWidth: 2440,
    standardSheetLength: 1220,
    primaryBoardThickness: 4,
    backPanelThickness: 3,
    sawKerf: 4.0,
    edgeBandingFront: 0,
    edgeBandingHidden: 0,
    doorReveal: 4,
    carcassConstruction: 'aluminium-box-frame',
    backPanelMount: 'infill-channel',
    grooveDepth: 0,
    grooveOffset: 0,
    standardBarLength: 6000,
    verticalFrameProfileId: 'KHASH-BOX-35',
    horizontalFrameProfileId: 'KHASH-BOX-35',
    doorFrameProfileId: 'KHASH-DOOR-55',
    cornerJointDeduction: 35,
    pricePerSheet: 650,
    pricePerProfileBar: 1110,
    costLaborPerMeter: 600,
    wasteFactorPercentage: 10,
  },

  // 5. نظام تصنيع غرف النوم والأسرّة والتسريحات (BEDROOMS MANUFACTURING SYSTEM)
  {
    id: 'sys-bedroom-wood-18',
    name: 'نظام تصنيع غرف النوم والأسرّة (MDF / ميلامين 18 مم و 25 مم)',
    nameEn: 'Bedroom Furniture & Bed Manufacturing System',
    systemType: 'wood',
    supportedCategories: ['bedroom'],
    description: 'تفصيل وتصنيع أسرّة كينج، شاسيهات المراتب، ظهر السرير المبطن، التسريحات والكومودينو مع قشاط ABS 2 مم للحواف المعرضة للاحتكاك',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 2.0, // 2mm ABS for bedroom furniture edges
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1750,
    pricePerProfileBar: 0,
    costLaborPerMeter: 400,
    wasteFactorPercentage: 12,
  },

  // 6. نظام غرف النوم الفاخرة - خشب طبيعي وقشرة أرو وجوز (LUXURY VENEER BEDROOM)
  {
    id: 'sys-bedroom-veneer-lux',
    name: 'نظام غرف النوم الفاخرة (قشرة خشب طبيعي أرو/جوز 18 مم)',
    nameEn: 'Luxury Natural Veneer Bedroom System',
    systemType: 'wood',
    supportedCategories: ['bedroom'],
    description: 'تصنيع أثاث غرف نوم فاخر من خشب إم دي إف مكسو قشرة طبيعية ودهانات بولي يوريثان مطفية وبانوهات بوكليه',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 2.0,
    edgeBandingHidden: 0.8,
    doorReveal: 2.5,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 10,
    grooveOffset: 18,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 2800,
    pricePerProfileBar: 0,
    costLaborPerMeter: 650,
    wasteFactorPercentage: 15,
  },

  // 7. نظام تصنيع الدريسينج روم وخزائن الملابس (DRESSING & WARDROBE SYSTEM)
  {
    id: 'sys-dressing-wardrobe-18',
    name: 'نظام تصنيع الدريسينج روم وخزائن الملابس (ألواح 18 مم)',
    nameEn: 'Dressing Room & Master Wardrobe System',
    systemType: 'wood',
    supportedCategories: ['dressing'],
    description: 'تفصيل قواطع الدريسينج الرأسية (Gables)، أرفف الملابس والأحذية، أدراج الساعات والمجوهرات، ومجاري الإضاءة المخفية',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 1.0,
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1700,
    pricePerProfileBar: 0,
    costLaborPerMeter: 380,
    wasteFactorPercentage: 12,
  },

  // 8. نظام تصنيع المكتبات ووحدات الشاشات الجدارية (LIBRARIES & TV MEDIA SYSTEM)
  {
    id: 'sys-library-slats-18',
    name: 'نظام تصنيع المكتبات ووحدات الشاشات والبانوهات (18 مم)',
    nameEn: 'Full Wall Library & Media Unit System',
    systemType: 'wood',
    supportedCategories: ['library'],
    description: 'تصنيع مكتبات الحوائط، تجاويف الشاشات الكبيرة، البانوهات الخشبية المضلعة، والأرفف الزجاجية والخشبية',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 1.0,
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1750,
    pricePerProfileBar: 0,
    costLaborPerMeter: 420,
    wasteFactorPercentage: 14,
  },

  // 9. نظام تصنيع أثاث الصالون وغرف المعيشة والسفرة (LIVING & DINING SYSTEM)
  {
    id: 'sys-living-dining-18',
    name: 'نظام تصنيع أثاث المعيشة والصالون والسفرة (18 مم و 25 مم)',
    nameEn: 'Living Room & Dining Furniture System',
    systemType: 'wood',
    supportedCategories: ['living', 'office', 'bathroom'],
    description: 'تصنيع طاولات القهوة، طاولات السفرة، بوفيهات التقديم، والمكاتب التنفيذية',
    standardSheetWidth: 2800,
    standardSheetLength: 2070,
    primaryBoardThickness: 18,
    backPanelThickness: 6,
    sawKerf: 3.5,
    edgeBandingFront: 2.0,
    edgeBandingHidden: 0.4,
    doorReveal: 3,
    carcassConstruction: 'sides-outside',
    backPanelMount: 'grooved',
    grooveDepth: 8,
    grooveOffset: 15,
    standardBarLength: 6000,
    cornerJointDeduction: 0,
    pricePerSheet: 1800,
    pricePerProfileBar: 0,
    costLaborPerMeter: 450,
    wasteFactorPercentage: 12,
  },
];
