import { ProjectData } from '../types';
import { 
  DEFAULT_MANUFACTURING_SETTINGS, 
  DEFAULT_COUNTERTOP_CONFIG, 
  DEFAULT_PLINTH_CONFIG, 
  DEFAULT_BACKSPLASH_CONFIG, 
  DEFAULT_MATERIAL_FINISHES,
  DEFAULT_PRICING_SETTINGS
} from './standards';

export const SAMPLE_PROJECT_MODERN_L: ProjectData = {
  metadata: {
    id: 'proj-modern-l',
    name: 'مطبخ مودرن حرف L مع برج أفران',
    clientName: 'أ / أحمد ومريم السيد',
    designerName: 'استوديو كيتشن كاد برو',
    date: '2026-08-27',
    notes: 'مطبخ مودرن هاندلس بدون مقابض، أسطح رخام كوارتز كلكتا جولد إيطالي، مع برج أفران وثلاجة بيلت إن متكاملة.',
    unit: 'cm',
  },
  room: {
    shape: 'rectangular',
    width: 4200,
    length: 3600,
    ceilingHeight: 2600,
    wallThickness: 150,
    walls: [
      { id: 'wall-a', name: 'الجدار أ (الخلفي)', startX: 0, startY: 0, endX: 4200, endY: 0, thickness: 150, height: 2600 },
      { id: 'wall-b', name: 'الجدار ب (الأيمن)', startX: 4200, startY: 0, endX: 4200, endY: 3600, thickness: 150, height: 2600 },
      { id: 'wall-c', name: 'الجدار ج (الأمامي)', startX: 4200, startY: 3600, endX: 0, endY: 3600, thickness: 150, height: 2600 },
      { id: 'wall-d', name: 'الجدار د (الأيسر)', startX: 0, startY: 3600, endX: 0, endY: 0, thickness: 150, height: 2600 },
    ],
    elements: [
      {
        id: 'win-01',
        name: 'نافذة المطبخ فوق الحوض',
        type: 'window',
        x: 1800,
        y: 0,
        z: 950,
        width: 1200,
        height: 1100,
        depth: 150,
        rotation: 0,
        wallId: 'wall-a',
      },
      {
        id: 'door-01',
        name: 'باب التراس والحديقة',
        type: 'door',
        x: 3500,
        y: 3600,
        z: 0,
        width: 900,
        height: 2100,
        depth: 150,
        rotation: 180,
        wallId: 'wall-c',
        openingDirection: 'inward-left',
      },
      {
        id: 'pipe-01',
        name: 'ماسورة التغذية والصرف',
        type: 'pipe',
        x: 2300,
        y: 100,
        z: 0,
        width: 150,
        height: 800,
        depth: 150,
        rotation: 0,
        wallId: 'wall-a',
      }
    ],
  },
  cabinets: [
    {
      id: 'T01',
      name: 'دولاب ثلاجة مدمجة',
      category: 'tall',
      type: 'tall-fridge-housing',
      width: 600,
      height: 2050,
      depth: 580,
      x: 0,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 1,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'right',
      customNotes: 'مخصص لتبييت ثلاجة بلت إن 178 سم',
    },
    {
      id: 'T02',
      name: 'برج أفران وميكروويف مدمج',
      category: 'tall',
      type: 'tall-oven-tower',
      width: 600,
      height: 2050,
      depth: 580,
      x: 600,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 2,
      doorCount: 2,
      drawerCount: 1,
      doorHinge: 'right',
      hasApplianceCavity: true,
      applianceCavityHeight: 600,
      applianceCavityZ: 780,
      customNotes: 'تجويف فرن بلت إن 60 سم',
    },
    {
      id: 'B01',
      name: 'سفلي 3 أدراج (معالق وحلل)',
      category: 'base',
      type: 'base-drawers-3',
      width: 600,
      height: 720,
      depth: 560,
      x: 1200,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 0,
      drawerCount: 3,
      doorHinge: 'none',
      customNotes: 'درج ملاعق علوي + درجين باستم هيدروليك',
    },
    {
      id: 'B02',
      name: 'وحدة حوض غسيل',
      category: 'base',
      type: 'base-sink',
      width: 800,
      height: 720,
      depth: 560,
      x: 1800,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
      hasSinkCutout: true,
      customNotes: 'موقع الحوض أسفل النافذة مباشرة',
    },
    {
      id: 'B03',
      name: 'غسالة صحون مدمجة',
      category: 'base',
      type: 'base-single-door',
      width: 600,
      height: 720,
      depth: 560,
      x: 2600,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'right',
      customNotes: 'واجهة خشبية لغسالة أطباق 60 سم',
    },
    {
      id: 'B04',
      name: 'وحدة ركنة زاوية L (90°)',
      category: 'corner',
      type: 'base-corner-l',
      width: 900,
      height: 720,
      depth: 900,
      x: 3200,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 1,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
      customNotes: 'سلال دوارة داخلية لومانز (LeMans II)',
    },

    // الجدار ب (الأيمن)
    {
      id: 'B05',
      name: 'سفلي مسطح طهي وبوتجاز (أدراج)',
      category: 'base',
      type: 'base-drawers-2',
      width: 900,
      height: 720,
      depth: 560,
      x: 4200 - 560,
      y: 900,
      z: 100,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 0,
      doorCount: 0,
      drawerCount: 2,
      doorHinge: 'none',
    },
    {
      id: 'B06',
      name: 'سفلي باب واحد للتخزين',
      category: 'base',
      type: 'base-single-door',
      width: 600,
      height: 720,
      depth: 560,
      x: 4200 - 560,
      y: 1800,
      z: 100,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 1,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'left',
    },

    // علوي الجدار ب
    {
      id: 'W01',
      name: 'علوي بابين مدمج بالشفاط',
      category: 'wall',
      type: 'wall-double-door',
      width: 900,
      height: 720,
      depth: 350,
      x: 4200 - 350,
      y: 900,
      z: 1450,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 2,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
    },
    {
      id: 'W02',
      name: 'علوي باب واحد تخزين',
      category: 'wall',
      type: 'wall-single-door',
      width: 600,
      height: 720,
      depth: 350,
      x: 4200 - 350,
      y: 1800,
      z: 1450,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 2,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'left',
    }
  ],
  appliances: [
    {
      id: 'A01',
      name: 'حوض ساقط بالرخام وخلاط شجرة نحاسي',
      type: 'sink-single',
      width: 600,
      height: 200,
      depth: 450,
      x: 1900,
      y: 100,
      z: 850,
      rotation: 0,
      wallId: 'wall-a',
    },
    {
      id: 'A02',
      name: 'مسطح طهي بلت إن 80 سم',
      type: 'cooktop-induction',
      width: 800,
      height: 50,
      depth: 520,
      x: 4200 - 500,
      y: 950,
      z: 850,
      rotation: 90,
      wallId: 'wall-b',
    },
    {
      id: 'A03',
      name: 'فرن بلت إن كهربائي 60 سم',
      type: 'oven-builtin',
      width: 595,
      height: 595,
      depth: 560,
      x: 600,
      y: 10,
      z: 880,
      rotation: 0,
      wallId: 'wall-a',
      finish: 'black',
    }
  ],
  architecturalElements: [],
  countertop: DEFAULT_COUNTERTOP_CONFIG,
  plinth: DEFAULT_PLINTH_CONFIG,
  backsplash: DEFAULT_BACKSPLASH_CONFIG,
  materials: DEFAULT_MATERIAL_FINISHES,
  manufacturing: DEFAULT_MANUFACTURING_SETTINGS,
  pricing: DEFAULT_PRICING_SETTINGS,
};
