import { ProjectData } from '../types';
import { 
  DEFAULT_MANUFACTURING_SETTINGS, 
  DEFAULT_COUNTERTOP_CONFIG, 
  DEFAULT_PLINTH_CONFIG, 
  DEFAULT_BACKSPLASH_CONFIG, 
  DEFAULT_MATERIAL_FINISHES 
} from './standards';

export const SAMPLE_PROJECT_MODERN_L: ProjectData = {
  metadata: {
    id: 'proj-modern-l',
    name: 'Modern L-Shape Residence',
    clientName: 'Sarah & David Miller',
    designerName: 'Studio ArchCAD Pro',
    date: '2026-08-27',
    notes: 'Premium handleless kitchen with integrated appliances, Calacatta quartz countertops and custom tall oven towers.',
    unit: 'mm',
  },
  room: {
    shape: 'rectangular',
    width: 4200,
    length: 3600,
    ceilingHeight: 2600,
    wallThickness: 150,
    walls: [
      { id: 'wall-a', name: 'Wall A (Back)', startX: 0, startY: 0, endX: 4200, endY: 0, thickness: 150, height: 2600 },
      { id: 'wall-b', name: 'Wall B (Right)', startX: 4200, startY: 0, endX: 4200, endY: 3600, thickness: 150, height: 2600 },
      { id: 'wall-c', name: 'Wall C (Front)', startX: 4200, startY: 3600, endX: 0, endY: 3600, thickness: 150, height: 2600 },
      { id: 'wall-d', name: 'Wall D (Left)', startX: 0, startY: 3600, endX: 0, endY: 0, thickness: 150, height: 2600 },
    ],
    elements: [
      {
        id: 'win-01',
        name: 'Garden Window',
        type: 'window',
        x: 1800,
        y: 0,
        z: 950,
        width: 1200,
        height: 1100,
        depth: 150,
        rotation: 0,
        wallId: 'wall-a',
      },
      {
        id: 'door-01',
        name: 'Terrace Glass Door',
        type: 'door',
        x: 3500,
        y: 3600,
        z: 0,
        width: 900,
        height: 2100,
        depth: 150,
        rotation: 180,
        wallId: 'wall-c',
        openingDirection: 'inward-left',
      },
      {
        id: 'pipe-01',
        name: 'Plumbing Supply / Drain',
        type: 'pipe',
        x: 2300,
        y: 100,
        z: 0,
        width: 150,
        height: 800,
        depth: 150,
        rotation: 0,
        wallId: 'wall-a',
      }
    ],
  },
  cabinets: [
    // --- Wall A (Back wall: Base cabinets from left to right) ---
    {
      id: 'T01',
      name: 'Integrated Fridge Housing',
      category: 'tall',
      type: 'tall-fridge-housing',
      width: 600,
      height: 2050,
      depth: 580,
      x: 0,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 1,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'right',
      customNotes: 'Houses 178cm Liebherr built-in fridge freezer',
    },
    {
      id: 'T02',
      name: 'Oven & Microwave Tower',
      category: 'tall',
      type: 'tall-oven-tower',
      width: 600,
      height: 2050,
      depth: 580,
      x: 600,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 2,
      doorCount: 2,
      drawerCount: 1,
      doorHinge: 'right',
      hasApplianceCavity: true,
      applianceCavityHeight: 600,
      applianceCavityZ: 780,
      customNotes: 'Miele 60cm single oven cavity',
    },
    {
      id: 'B01',
      name: '3-Drawer Base Unit',
      category: 'base',
      type: 'base-drawers-3',
      width: 600,
      height: 720,
      depth: 560,
      x: 1200,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 0,
      drawerCount: 3,
      doorHinge: 'none',
      customNotes: 'Cutlery insert top drawer, Blum Legrabox soft-close',
    },
    {
      id: 'B02',
      name: 'Sink Base Unit',
      category: 'base',
      type: 'base-sink',
      width: 800,
      height: 720,
      depth: 560,
      x: 1800,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
      hasSinkCutout: true,
      customNotes: 'Under-window sink placement, Blanco undermount basin',
    },
    {
      id: 'B03',
      name: 'Integrated Dishwasher',
      category: 'base',
      type: 'base-single-door',
      width: 600,
      height: 720,
      depth: 560,
      x: 2600,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 0,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'right',
      customNotes: 'Fully integrated 60cm dishwasher front panel',
    },
    {
      id: 'B04',
      name: 'Corner Base Unit (90°)',
      category: 'corner',
      type: 'base-corner-l',
      width: 900,
      height: 720,
      depth: 900,
      x: 3200,
      y: 0,
      z: 100,
      rotation: 0,
      wallId: 'wall-a',
      shelfCount: 1,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
      customNotes: 'LeMans II pullout swivel baskets',
    },

    // --- Wall B (Right Wall: Cooktop zone) ---
    {
      id: 'B05',
      name: 'Induction Cooktop Base (Drawers)',
      category: 'base',
      type: 'base-drawers-2',
      width: 900,
      height: 720,
      depth: 560,
      x: 4200 - 560,
      y: 900,
      z: 100,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 0,
      doorCount: 0,
      drawerCount: 2,
      doorHinge: 'none',
      customNotes: 'Heavy-duty 70kg pan drawer slides',
    },
    {
      id: 'B06',
      name: 'Single Door Base Unit',
      category: 'base',
      type: 'base-single-door',
      width: 600,
      height: 720,
      depth: 560,
      x: 4200 - 560,
      y: 1800,
      z: 100,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 1,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'left',
    },

    // --- Wall Units on Wall B ---
    {
      id: 'W01',
      name: 'Double Door Wall Unit',
      category: 'wall',
      type: 'wall-double-door',
      width: 900,
      height: 720,
      depth: 350,
      x: 4200 - 350,
      y: 900,
      z: 1450,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 2,
      doorCount: 2,
      drawerCount: 0,
      doorHinge: 'double',
      customNotes: 'Concealed canopy extractor hood integrated inside',
    },
    {
      id: 'W02',
      name: 'Single Door Wall Unit',
      category: 'wall',
      type: 'wall-single-door',
      width: 600,
      height: 720,
      depth: 350,
      x: 4200 - 350,
      y: 1800,
      z: 1450,
      rotation: 90,
      wallId: 'wall-b',
      shelfCount: 2,
      doorCount: 1,
      drawerCount: 0,
      doorHinge: 'left',
    }
  ],
  appliances: [
    {
      id: 'A01',
      name: 'Under-mount Sink & Brass Faucet',
      type: 'sink-single',
      width: 600,
      height: 200,
      depth: 450,
      x: 1900,
      y: 100,
      z: 850,
      rotation: 0,
      wallId: 'wall-a',
    },
    {
      id: 'A02',
      name: '80cm Induction Cooktop',
      type: 'cooktop-induction',
      width: 800,
      height: 50,
      depth: 520,
      x: 4200 - 500,
      y: 950,
      z: 850,
      rotation: 90,
      wallId: 'wall-b',
    },
    {
      id: 'A03',
      name: 'Built-in Convection Oven',
      type: 'oven-builtin',
      width: 595,
      height: 595,
      depth: 560,
      x: 600,
      y: 10,
      z: 880,
      rotation: 0,
      wallId: 'wall-a',
      finish: 'black',
    }
  ],
  architecturalElements: [],
  countertop: DEFAULT_COUNTERTOP_CONFIG,
  plinth: DEFAULT_PLINTH_CONFIG,
  backsplash: DEFAULT_BACKSPLASH_CONFIG,
  materials: DEFAULT_MATERIAL_FINISHES,
  manufacturing: DEFAULT_MANUFACTURING_SETTINGS,
};
