import { WardrobeCategory, CabinetType, WardrobeDoorType } from '../types';

export interface WardrobeTemplate {
  category: WardrobeCategory;
  type: CabinetType;
  name: string;
  nameEn: string;
  description: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultDepth: number;
  defaultZ: number;
  doorCount: number;
  doorType: WardrobeDoorType;
  drawerCount: number;
  shelfCount: number;
  standardWidths: number[];
  icon: string;
  hasHangingRail?: boolean;
  hangingRailCount?: number;
  hasShoeShelves?: boolean;
  hasJewelryDrawer?: boolean;
  hasTrouserRack?: boolean;
  hasLaundryBasket?: boolean;
  slidingTracksCount?: number;
  hasIntegratedLed?: boolean;
  verticalDividersCount?: number;
  isCeilingUnit?: boolean;
  tag?: string;
}

export const WARDROBE_LIBRARY: WardrobeTemplate[] = [
  // =========================================================================
  // 0. علب ووحدات الدريسينج الموديلار (MODULAR DRESSING CARCASSES & UNITS)
  // =========================================================================
  {
    category: 'wardrobe',
    type: 'wardrobe-hinged-2d',
    name: 'علبة دريسنج معيارية بضلفتين (قابلة للتعديل والتحويل)',
    nameEn: 'Modular 2-Door Dressing Carcass',
    description: 'علبة دريسنج قياسية يمكن تعديل مقاساتها بالكامل أو إزالة الضلف أو جعلها ثابتة أو زجاجية',
    defaultWidth: 900,
    defaultHeight: 2400,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 2,
    shelfCount: 3,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'DoorClosed',
    tag: 'علبة دريسنج 2 ضلفة',
  },
  {
    category: 'wardrobe',
    type: 'wall-single-door',
    name: 'علبة دريسنج مفردة ضلفة واحدة (Single Door Dressing)',
    nameEn: 'Modular 1-Door Dressing Carcass',
    description: 'علبة دريسنج مفردة ضلفة واحدة يمكن فتحها يمين أو يسار أو تحويلها لضلفة ثابتة أو مفتوحة',
    defaultWidth: 500,
    defaultHeight: 2400,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 1,
    doorType: 'hinged',
    drawerCount: 0,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [400, 450, 500, 600],
    icon: 'DoorClosed',
    tag: 'علبة دريسنج ضلفة',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-hinged-2d',
    name: 'علبة دريسنج بضلفة ثابتة / بانوه تكميلي (Fixed Door Unit)',
    nameEn: 'Fixed Door / Panel Dressing Unit',
    description: 'وحدة دريسنج بضلفة ثابتة (Fixed Door) لا تفتح، مخصصة للفيلرات المعمارية وتقفيل الزوايا والواجهات',
    defaultWidth: 450,
    defaultHeight: 2400,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 1,
    doorType: 'fixed',
    drawerCount: 0,
    shelfCount: 4,
    standardWidths: [300, 400, 450, 500, 600],
    icon: 'Square',
    tag: 'ضلفة ثابتة Fixed',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-walkin-open',
    name: 'علبة دريسنج مفتوحة بدون ضلف (Open Walk-in Carcass)',
    nameEn: 'Open Modular Dressing Unit',
    description: 'علبة دريسنج مفتوحة تماماً بدون أبواب مع رفوف قابلة للتعديل وماسورة تعليق وأدراج داخلية',
    defaultWidth: 800,
    defaultHeight: 2400,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 2,
    shelfCount: 3,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Shirt',
    tag: 'دريسنج مفتوح',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-glass-doors',
    name: 'علبة دريسنج زجاج فريم ألومنيوم مع إضاءة (Glass Frame)',
    nameEn: 'Aluminium Glass Frame Dressing Unit',
    description: 'علبة دريسنج فاخرة بضلف زجاجية وإطار بروفايل ألومنيوم أنيق مع إضاءة خطية LED',
    defaultWidth: 1000,
    defaultHeight: 2600,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'glass-frame',
    drawerCount: 2,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 1,
    hasIntegratedLed: true,
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Sparkles',
    tag: 'دريسنج زجاج',
  },
  {
    category: 'wardrobe',
    type: 'wall-loft-deep',
    name: 'علبة دريسنج علوية تقفيل سقف (Loft Unit)',
    nameEn: 'Dressing Top Loft Unit',
    description: 'علبة علوية تكنة سقف لتخزين الحقائب والبطانيات مع ضلفتين عاديتين أو قلاب أو ضلفة ثابتة',
    defaultWidth: 900,
    defaultHeight: 500,
    defaultDepth: 600,
    defaultZ: 2100,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 0,
    shelfCount: 1,
    isCeilingUnit: true,
    standardWidths: [600, 800, 900, 1000, 1200],
    icon: 'Layers',
    tag: 'تكنة علوية',
  },

  // =========================================================================
  // 1. دواليب مفتوحة ودريسنج ماستر (OPEN WALK-IN WARDROBES)
  // =========================================================================
  {
    category: 'wardrobe',
    type: 'wardrobe-walkin-open',
    name: 'وحدة تعليق طويل للفساتين والعبايات (Long Dress Rail)',
    nameEn: 'Open Walk-in Long Dress Hanging Unit',
    description: 'دريسنج مفتوح مع ماسورة تعليق للعبايات والفساتين الطويلة مع رف علوي للحقائب',
    defaultWidth: 1000,
    defaultHeight: 2600,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 2,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Shirt',
    tag: 'تعليق فساتين',
  },
  {
    category: 'closet-internals',
    type: 'wardrobe-hanging-double',
    name: 'وحدة تعليق مزدوج للقمصان والبدل (Double Suit Rail)',
    nameEn: 'Open Double Hanging Suit Unit',
    description: 'ماسورتان تعليق علوية وسفلية لمضاعفة سعة تخزين القمصان والبدل والجاكتات',
    defaultWidth: 900,
    defaultHeight: 2600,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 2,
    hasHangingRail: true,
    hangingRailCount: 2,
    standardWidths: [800, 900, 1000, 1200],
    icon: 'Columns2',
    tag: 'تعليق قمصان',
  },
  {
    category: 'closet-internals',
    type: 'wardrobe-shelves-drawers',
    name: 'برج أدراج ومطبق ملابس (4 أدراج + 4 أرفف)',
    nameEn: 'Shelves & 4-Drawer Tower',
    description: 'برج تخزين متكامل يجمع بين 4 أدراج عميقة للملابس الداخلية و 4 أرفف للملابس المطوية',
    defaultWidth: 800,
    defaultHeight: 2600,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 4,
    shelfCount: 4,
    standardWidths: [600, 800, 900, 1000],
    icon: 'Rows3',
    tag: 'أدراج ومطبق',
  },
  {
    category: 'accessories',
    type: 'wardrobe-shoe-rack',
    name: 'فيترينة أرفف أحذية مائلة مع حاجز ستانلس (8 رفوف)',
    nameEn: 'Slanted Shoe Rack Tower with LED',
    description: 'أرفف أحذية مائلة بزاوية هندسية مع شفة ألومنيوم مانعة للانزلاق وإضاءة LED جانبية',
    defaultWidth: 800,
    defaultHeight: 2600,
    defaultDepth: 400,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 8,
    hasShoeShelves: true,
    hasIntegratedLed: true,
    standardWidths: [600, 800, 900, 1000],
    icon: 'Footprints',
    tag: 'أحذية',
  },
  {
    category: 'accessories',
    type: 'wardrobe-trouser-rack',
    name: 'وحدة حامل بناطيل سحاب ميكانيكي (Trouser Pullout)',
    nameEn: 'Pullout Trouser & Pants Rack Unit',
    description: 'مجهزة بميكانيزم سحاب هيدروليك يحمل 10 قضبان بناطيل مع مانع انزلاق مطاطي',
    defaultWidth: 800,
    defaultHeight: 2600,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 2,
    shelfCount: 3,
    hasTrouserRack: true,
    standardWidths: [600, 800, 900],
    icon: 'Sliders',
    tag: 'بناطيل',
  },
  {
    category: 'accessories',
    type: 'wardrobe-jewelry-vanity',
    name: 'جزيرة دريسنج مركزية مع درج إكسسوارات وساعات وسطح زجاج',
    nameEn: 'Dressing Island with Velvet Jewelry Tray',
    description: 'جزيرة دريسنج فاخرة بـ 6 أدراج مع درج علوي مقسم للمجوهرات والساعات وسطح زجاجي شفاف',
    defaultWidth: 1200,
    defaultHeight: 900,
    defaultDepth: 700,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 6,
    shelfCount: 0,
    hasJewelryDrawer: true,
    standardWidths: [1000, 1200, 1400, 1600],
    icon: 'Sparkles',
    tag: 'جزيرة دريسنج',
  },
  {
    category: 'accessories',
    type: 'wardrobe-laundry-hamper',
    name: 'وحدة سلال غسيل ومفارش سحابة (Laundry Baskets)',
    nameEn: 'Pullout Double Laundry Hamper Unit',
    description: 'سلتان قماش أو سلك ستانلس سحاب لفرز الملابس البيضاء والملونة',
    defaultWidth: 600,
    defaultHeight: 2600,
    defaultDepth: 550,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 1,
    shelfCount: 3,
    hasLaundryBasket: true,
    standardWidths: [500, 600, 800],
    icon: 'Package',
    tag: 'غسيل',
  },
  {
    category: 'accessories',
    type: 'wardrobe-bags-vitrine',
    name: 'فيترينة حقائب يد واكسسوارات مضيئة (Bags Cubbies)',
    nameEn: 'Luxury Handbag Showcase with LED Cubbies',
    description: 'مكعبات وقواطع مفتوحة مخصصة لعرض شنط اليد النسائية مع إضاءة ليد بروفايل دافئة',
    defaultWidth: 800,
    defaultHeight: 2600,
    defaultDepth: 450,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 6,
    verticalDividersCount: 1,
    hasIntegratedLed: true,
    standardWidths: [800, 900, 1000],
    icon: 'Layers',
    tag: 'حقائب',
  },

  // =========================================================================
  // 2. دواليب مفصلية وسحاب (HINGED & SLIDING WARDROBES)
  // =========================================================================
  {
    category: 'wardrobe',
    type: 'wardrobe-hinged-2d',
    name: 'دولاب ملابس مفصلي ضلفتين كلاسيك',
    nameEn: '2-Door Hinged Wardrobe',
    description: 'دولاب ملابس قياسي ببابين مفصليين مع ماسورة تعليق ملابس ورف علوي للحقائب',
    defaultWidth: 1000,
    defaultHeight: 2400,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 0,
    shelfCount: 2,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [800, 900, 1000, 1200],
    icon: 'DoorClosed',
    tag: 'مفصلي',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-sliding-2d',
    name: 'دولاب جرار ضلفتين سحاب هيدروليك',
    nameEn: '2-Door Sliding Wardrobe',
    description: 'دولاب جرار لتوفير المساحة بضلفتين سحاب مع مجاري هيدروليك مانع صدمات سوفت كلوز',
    defaultWidth: 1800,
    defaultHeight: 2400,
    defaultDepth: 650,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'sliding',
    drawerCount: 2,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 2,
    slidingTracksCount: 2,
    standardWidths: [1600, 1800, 2000, 2200],
    icon: 'ArrowRightLeft',
    tag: 'سحاب جرار',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-glass-doors',
    name: 'دولاب زجاج رمادي مدخن فريم ألومنيوم وإضاءة LED',
    nameEn: 'Smoked Glass Aluminium Profile Wardrobe',
    description: 'دولاب ملابس فندقي فاخر بأبواب زجاجية شفافة فريم ألومنيوم أسود وإضاءة خطية كاملة',
    defaultWidth: 1200,
    defaultHeight: 2600,
    defaultDepth: 600,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 2,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 1,
    hasIntegratedLed: true,
    standardWidths: [1000, 1200, 1500, 1800],
    icon: 'Sparkles',
    tag: 'زجاج مودرن',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-corner-open',
    name: 'دولاب دريسنج ركنة حرف L مفتوح ماستر (Walk-in Corner)',
    nameEn: 'L-Shaped Open Walk-In Corner Wardrobe',
    description: 'وحدة زاوية قائمة مفتوحة بالكامل 100×100 سم مع ماسورتين تعليق متقاطعتين لاستغلال زاوية الدريسنج بدون هدر',
    defaultWidth: 1000,
    defaultHeight: 2600,
    defaultDepth: 1000,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 2,
    standardWidths: [900, 1000, 1100, 1200],
    icon: 'CornerDownRight',
    tag: 'ركنة دريسنج L',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-corner-mirror-45',
    name: 'دولاب دريسنج ركنة زاوية 45° مع مرآة كاملة (Mirror 45° Corner)',
    nameEn: '45-Degree Beveled Corner Wardrobe with Full Mirror',
    description: 'دولاب زاوية مشطوف بزاوية 45 درجة مع باب مرآة كاملة بروفايل وإضاءة ليد محيطية',
    defaultWidth: 1050,
    defaultHeight: 2600,
    defaultDepth: 1050,
    defaultZ: 0,
    doorCount: 1,
    doorType: 'hinged',
    drawerCount: 2,
    shelfCount: 5,
    hasHangingRail: true,
    hangingRailCount: 1,
    hasIntegratedLed: true,
    standardWidths: [950, 1050, 1150],
    icon: 'Maximize2',
    tag: 'ركنة مرآة 45°',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-corner-carousel',
    name: 'برج ركنة دريسنج دوار 360° للأحذية والشنط (Rotating Carousel)',
    nameEn: '360° Rotating Shoe & Bag Corner Carousel Unit',
    description: 'ميكانيزم ركنة دائري يدور 360 درجة بـ 8 طوابق لعرض 40 زوج أحذية وحقائب يد',
    defaultWidth: 950,
    defaultHeight: 2600,
    defaultDepth: 950,
    defaultZ: 0,
    doorCount: 0,
    doorType: 'open',
    drawerCount: 0,
    shelfCount: 8,
    hasShoeShelves: true,
    hasIntegratedLed: true,
    standardWidths: [900, 950, 1000],
    icon: 'RotateCw',
    tag: 'ركنة دوارة 360°',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-corner-glass',
    name: 'دولاب ركنة زاوية زجاج مدخن بضلفة طي (Glass Bi-Fold Corner)',
    nameEn: 'Smoked Glass Bi-Fold Corner Dressing Unit',
    description: 'دولاب زاوية فخم بأبواب زجاجية قابلة للطي بزاوية 180 درجة وإضاءة خطية LED مدمجة',
    defaultWidth: 1000,
    defaultHeight: 2600,
    defaultDepth: 1000,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 2,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 2,
    hasIntegratedLed: true,
    standardWidths: [950, 1000, 1100],
    icon: 'Sparkles',
    tag: 'ركنة زجاج L',
  },
  {
    category: 'wardrobe',
    type: 'wardrobe-corner-l',
    name: 'دولاب ركنة زاوية كلاسيك للدريسنج (Corner Wardrobe 90°)',
    nameEn: 'L-Shaped Corner Dressing Unit',
    description: 'وحدة زاوية قائمة تستغل أركان غرفة الملابس بكفاءة مع أرفف عميقة وعلاقة زاوية',
    defaultWidth: 1000,
    defaultHeight: 2600,
    defaultDepth: 1000,
    defaultZ: 0,
    doorCount: 2,
    doorType: 'hinged',
    drawerCount: 0,
    shelfCount: 4,
    hasHangingRail: true,
    hangingRailCount: 1,
    standardWidths: [950, 1000, 1100],
    icon: 'CornerDownRight',
    tag: 'ركنة زاوية',
  },
];
